#!/bin/sh
set -e
echo STARTING...
if [ -z "$PORT" ]; then PORT=2244; fi
export PORT
if [ ! -f $SNAP_DATA/hello.conf ]; then
    touch $SNAP_DATA/hello.conf
    echo "NEW - Copy settings.js to "$SNAP_DATA
    cp $SNAP/bin/conf/settings.js $SNAP_DATA/
    cp $SNAP/bin/conf/flows.json $SNAP_COMMON/
    cp -r $SNAP/bin/conf/js $SNAP_COMMON/js
    cp -r $SNAP/bin/conf/css $SNAP_COMMON/css
    mkdir $SNAP_DATA/node_modules
    cp -r $SNAP/lib/node_modules/lodash $SNAP_DATA/node_modules
    cp $SNAP/bin/conf/package.json $SNAP_DATA/
fi
echo NOW STARTING NODE-RED : $SNAP/bin/node-red -u $SNAP_DATA on port $PORT
"$SNAP"/bin/node "$SNAP"/lib/node_modules/.bin/node-red -u "$SNAP_DATA" "$SNAP_COMMON/flows.json"